import type { Metadata } from "next";
import { Bellefair, Barlow_Condensed, Barlow } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTrigger,
} from "@/components/ui/sheet";
import { Separator } from "@/components/ui/separator";

const berllefair = Bellefair({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bellefair",
  display: "swap",
});

const barlowCondensed = Barlow_Condensed({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-barlow-condensed",
  display: "swap",
});

const barlow = Barlow({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-barlow",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${berllefair.variable} ${barlowCondensed.variable} ${barlow.variable}`}
      >
        <header className="flex justify-between xl:grid xl:grid-cols-2 md:justify-normal md:items-center p-6 md:p-0 absolute w-full lg:mt-10">
          <div className="md:px-10 lg:ps-16 lg:pe-0 lg:flex">
            <Link href="/">
              <Image
                alt="Icon"
                src={"/assets/shared/logo.svg"}
                width={40}
                height={40}
                className="md:w-12 md:h-12"
              />
            </Link>
            <div className="hidden lg:flex-grow lg:relative lg:flex lg:items-center">
              <Separator className="bg-white/15 h-[2px] relative xl:absolute left-16 w-[22vw] xl:w-[97.5%] z-10" />
            </div>
          </div>
          <Sheet>
            <SheetTrigger className="md:hidden">
              <Image
                alt="Icon"
                src={"/assets/shared/icon-hamburger.svg"}
                width={24}
                height={24}
              />
            </SheetTrigger>
            <SheetContent className="">
              <SheetHeader>
                <SheetDescription className="grid gap-8 text-white text-left ms-8">
                  <Link href={"/"} className="preset-8">
                    <span className="font-bold">00</span>&nbsp; HOME
                  </Link>
                  <Link href={"/destination"} className="preset-8">
                    <span className="font-bold">01</span>&nbsp; DESTINATION
                  </Link>
                  <Link href={"/crew"} className="preset-8">
                    <span className="font-bold">02</span>&nbsp; CREW
                  </Link>
                  <Link href={"/technology"} className="preset-8">
                    <span className="font-bold">03</span>&nbsp; TECHNOLOGY
                  </Link>
                </SheetDescription>
              </SheetHeader>
            </SheetContent>
          </Sheet>
          <div className="hidden md:flex md:flex-row-reverse md:gap-11 md:items-center md:flex-grow bg-white/5 backdrop-blur-2xl pe-10 ps-10 lg:ps-16 lg:pe-16 py-10">
            <Link href={"/technology"} className="preset-8">
              <span className="font-bold">03</span>&nbsp; TECHNOLOGY
            </Link>
            <Link href={"/crew"} className="preset-8">
              <span className="font-bold">02</span>&nbsp; CREW
            </Link>
            <Link href={"/destination"} className="preset-8">
              <span className="font-bold">01</span>&nbsp; DESTINATION
            </Link>
            <Link href={"/"} className="preset-8">
              <span className="font-bold">00</span>&nbsp; HOME
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
